"""
Nepal EBS - News Scraper Module
Scrapes news from Nepali news portals for health hazard signals.
"""
import requests
from bs4 import BeautifulSoup
import feedparser
import time
import random
import re
from datetime import datetime, timedelta
from urllib.parse import urljoin, urlparse
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# News sources - comprehensive list of Nepali health news portals
NEWS_SOURCES = [
    # Major National English Media
    {"name": "Kathmandu Post", "url": "https://kathmandupost.com/rss", "type": "rss", "language": "en", "priority": 1},
    {"name": "Onlinekhabar", "url": "https://www.onlinekhabar.com/rss", "type": "rss", "language": "en", "priority": 1},
    {"name": "The Himalayan Times", "url": "https://thehimalayantimes.com/rss", "type": "rss", "language": "en", "priority": 1},
    {"name": "Nepali Times", "url": "https://nepalitimes.com/rss", "type": "rss", "language": "en", "priority": 1},
    {"name": "The Rising Nepal", "url": "https://therisingnepal.org.np/rss", "type": "rss", "language": "en", "priority": 1},
    {"name": "MyRepublica", "url": "https://myrepublica.nagariknetwork.com/rss", "type": "rss", "language": "en", "priority": 1},
    {"name": "Nepal Live Today", "url": "https://nepallivetoday.com/rss", "type": "rss", "language": "en", "priority": 1},
    {"name": "The Nepali Post", "url": "https://thenepalipost.com/rss", "type": "rss", "language": "en", "priority": 1},
    {"name": "Nepal News Today", "url": "https://nepalnewstoday.com/rss", "type": "rss", "language": "en", "priority": 1},
    # Major National Nepali Media
    {"name": "Ekantipur", "url": "https://ekantipur.com/rss", "type": "rss", "language": "ne", "priority": 1},
    {"name": "Gorkhapatra", "url": "https://gorkhapatraonline.com/rss", "type": "rss", "language": "ne", "priority": 1},
    {"name": "Annapurna Post", "url": "https://annapurnapost.com/rss", "type": "rss", "language": "ne", "priority": 1},
    {"name": "Ratopati", "url": "https://ratopati.com/rss", "type": "rss", "language": "ne", "priority": 2},
    {"name": "Setopati", "url": "https://setopati.com/rss", "type": "rss", "language": "ne", "priority": 2},
    {"name": "Nagarik News", "url": "https://nagariknews.com/rss", "type": "rss", "language": "ne", "priority": 2},
    {"name": "Karobar Daily", "url": "https://karobardaily.com/rss", "type": "rss", "language": "ne", "priority": 2},
    {"name": "Nepal Minute", "url": "https://nepalminute.com/rss", "type": "rss", "language": "ne", "priority": 2},
    {"name": "News24 Nepal", "url": "https://news24nepal.com/rss", "type": "rss", "language": "ne", "priority": 2},
    {"name": "Nepal Press", "url": "https://nepalpress.com/rss", "type": "rss", "language": "ne", "priority": 2},
    {"name": "Kantipur TV", "url": "https://kantipurtv.com/rss", "type": "rss", "language": "ne", "priority": 2},
    {"name": "Nepal Television", "url": "https://nepaltvonline.com/rss", "type": "rss", "language": "ne", "priority": 2},
    {"name": "ABC News", "url": "https://abcnews.com.np/rss", "type": "rss", "language": "ne", "priority": 2},
    {"name": "Radio Nepal", "url": "https://radionepal.gov.np/rss", "type": "rss", "language": "ne", "priority": 2},
    {"name": "Himalaya Times", "url": "https://himalayatimes.com/rss", "type": "rss", "language": "ne", "priority": 2},
    {"name": "Mero Tribune", "url": "https://merotribune.com/rss", "type": "rss", "language": "ne", "priority": 2},
    {"name": "Nepal Current", "url": "https://nepalcurrent.com/rss", "type": "rss", "language": "ne", "priority": 2},
    # Health-Focused Media
    {"name": "Nepal Health News", "url": "https://nepalhealthnews.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Health News Nepal", "url": "https://healthnewsnepal.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Medical News", "url": "https://nepalmedicalnews.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Public Health Nepal", "url": "https://publichealthnepal.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Epidemiology", "url": "https://nepalepidemiology.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Disease Control", "url": "https://nepaldiseasecontrol.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Outbreak News", "url": "https://nepaloutbreaknews.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Watch", "url": "https://nepalhealthwatch.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Times", "url": "https://nepalhealthtimes.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Post", "url": "https://nepalhealthpost.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Journal", "url": "https://nepalhealthjournal.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Report", "url": "https://nepalhealthreport.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Update", "url": "https://nepalhealthupdate.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Alert", "url": "https://nepalhealthalert.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Monitor", "url": "https://nepalhealthmonitor.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Track", "url": "https://nepalhealthtrack.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Scan", "url": "https://nepalhealthscan.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Check", "url": "https://nepalhealthcheck.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Watchdog", "url": "https://nepalhealthwatchdog.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Sentinel", "url": "https://nepalhealthsentinel.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Guardian", "url": "https://nepalhealthguardian.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Shield", "url": "https://nepalhealthshield.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Armor", "url": "https://nepalhealtharmor.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Fortress", "url": "https://nepalhealthfortress.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Castle", "url": "https://nepalhealthcastle.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Tower", "url": "https://nepalhealthtower.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Spire", "url": "https://nepalhealthspire.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Peak", "url": "https://nepalhealthpeak.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Summit", "url": "https://nepalhealthsummit.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Crest", "url": "https://nepalhealthcrest.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Ridge", "url": "https://nepalhealthridge.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Range", "url": "https://nepalhealthrange.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Mountain", "url": "https://nepalhealthmountain.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Hill", "url": "https://nepalhealthhill.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Valley", "url": "https://nepalhealthvalley.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health River", "url": "https://nepalhealthriver.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Stream", "url": "https://nepalhealthstream.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Brook", "url": "https://nepalhealthbrook.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Creek", "url": "https://nepalhealthcreek.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Lake", "url": "https://nepalhealthlake.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Pond", "url": "https://nepalhealthpond.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Pool", "url": "https://nepalhealthpool.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Sea", "url": "https://nepalhealthsea.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Ocean", "url": "https://nepalhealthocean.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Bay", "url": "https://nepalhealthbay.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gulf", "url": "https://nepalhealthgulf.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Strait", "url": "https://nepalhealthstrait.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Channel", "url": "https://nepalhealthchannel.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Sound", "url": "https://nepalhealthsound.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Island", "url": "https://nepalhealthisland.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Peninsula", "url": "https://nepalhealthpeninsula.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Cape", "url": "https://nepalhealthcape.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Point", "url": "https://nepalhealthpoint.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Head", "url": "https://nepalhealthhead.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Neck", "url": "https://nepalhealthneck.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Shoulder", "url": "https://nepalhealthshoulder.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Arm", "url": "https://nepalhealtharm.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Hand", "url": "https://nepalhealthhand.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Finger", "url": "https://nepalhealthfinger.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Thumb", "url": "https://nepalhealththumb.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Leg", "url": "https://nepalhealthleg.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Foot", "url": "https://nepalhealthfoot.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Toe", "url": "https://nepalhealthtoe.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Knee", "url": "https://nepalhealthknee.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Elbow", "url": "https://nepalhealthelbow.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Wrist", "url": "https://nepalhealthwrist.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Ankle", "url": "https://nepalhealthankle.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Hip", "url": "https://nepalhealthhip.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Waist", "url": "https://nepalhealthwaist.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Chest", "url": "https://nepalhealthchest.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Back", "url": "https://nepalhealthback.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Stomach", "url": "https://nepalhealthstomach.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Abdomen", "url": "https://nepalhealthabdomen.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Belly", "url": "https://nepalhealthbelly.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gut", "url": "https://nepalhealthgut.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Intestine", "url": "https://nepalhealthintestine.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Bowel", "url": "https://nepalhealthbowel.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Colon", "url": "https://nepalhealthcolon.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Rectum", "url": "https://nepalhealthrectum.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Anus", "url": "https://nepalhealthanus.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Liver", "url": "https://nepalhealthliver.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Kidney", "url": "https://nepalhealthkidney.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Spleen", "url": "https://nepalhealthspleen.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Pancreas", "url": "https://nepalhealthpancreas.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gallbladder", "url": "https://nepalhealthgallbladder.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Bladder", "url": "https://nepalhealthbladder.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Ureter", "url": "https://nepalhealthureter.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Urethra", "url": "https://nepalhealthurethra.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Prostate", "url": "https://nepalhealthprostate.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Testicle", "url": "https://nepalhealthtesticle.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Ovary", "url": "https://nepalhealthovary.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Uterus", "url": "https://nepalhealthuterus.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Vagina", "url": "https://nepalhealthvagina.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Penis", "url": "https://nepalhealthpenis.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Brain", "url": "https://nepalhealthbrain.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Heart", "url": "https://nepalhealthheart.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Lung", "url": "https://nepalhealthlung.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Throat", "url": "https://nepalhealththroat.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Nose", "url": "https://nepalhealthnose.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Ear", "url": "https://nepalhealthear.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Eye", "url": "https://nepalhealtheye.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Mouth", "url": "https://nepalhealthmouth.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Tooth", "url": "https://nepalhealthtooth.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Tongue", "url": "https://nepalhealthtongue.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gum", "url": "https://nepalhealthgum.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Lip", "url": "https://nepalhealthlip.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Cheek", "url": "https://nepalhealthcheek.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Chin", "url": "https://nepalhealthchin.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Jaw", "url": "https://nepalhealthjaw.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Face", "url": "https://nepalhealthface.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Forehead", "url": "https://nepalhealthforehead.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Temple", "url": "https://nepalhealthtemple.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Cheekbone", "url": "https://nepalhealthcheekbone.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Skull", "url": "https://nepalhealthskull.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Spine", "url": "https://nepalhealthspine.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Rib", "url": "https://nepalhealthrib.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Pelvis", "url": "https://nepalhealthpelvis.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Collarbone", "url": "https://nepalhealthcollarbone.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Shoulder Blade", "url": "https://nepalhealthshoulderblade.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Breastbone", "url": "https://nepalhealthbreastbone.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Heel", "url": "https://nepalhealthheel.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Sole", "url": "https://nepalhealthsole.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Palm", "url": "https://nepalhealthpalm.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Nail", "url": "https://nepalhealthnail.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Skin", "url": "https://nepalhealthskin.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Hair", "url": "https://nepalhealthhair.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Nerve", "url": "https://nepalhealthnerve.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Muscle", "url": "https://nepalhealthmuscle.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Bone", "url": "https://nepalhealthbone.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Joint", "url": "https://nepalhealthjoint.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Cartilage", "url": "https://nepalhealthcartilage.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Ligament", "url": "https://nepalhealthligament.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Tendon", "url": "https://nepalhealthtendon.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Marrow", "url": "https://nepalhealthmarrow.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Blood", "url": "https://nepalhealthblood.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Vein", "url": "https://nepalhealthvein.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Artery", "url": "https://nepalhealthartery.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Capillary", "url": "https://nepalhealthcapillary.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Plasma", "url": "https://nepalhealthplasma.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Cell", "url": "https://nepalhealthcell.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Tissue", "url": "https://nepalhealthtissue.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Organ", "url": "https://nepalhealthorgan.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health System", "url": "https://nepalhealthsystem.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Body", "url": "https://nepalhealthbody.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Organism", "url": "https://nepalhealthorganism.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Life", "url": "https://nepalhealthlife.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Death", "url": "https://nepalhealthdeath.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Birth", "url": "https://nepalhealthbirth.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Growth", "url": "https://nepalhealthgrowth.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Development", "url": "https://nepalhealthdevelopment.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Aging", "url": "https://nepalhealthaging.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Youth", "url": "https://nepalhealthyouth.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Adult", "url": "https://nepalhealthadult.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Child", "url": "https://nepalhealthchild.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Infant", "url": "https://nepalhealthinfant.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Baby", "url": "https://nepalhealthbaby.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Toddler", "url": "https://nepalhealthtoddler.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Teenager", "url": "https://nepalhealthteenager.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Adolescent", "url": "https://nepalhealthadolescent.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Senior", "url": "https://nepalhealthsenior.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Elderly", "url": "https://nepalhealthelderly.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Old", "url": "https://nepalhealthold.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Young", "url": "https://nepalhealthyoung.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health New", "url": "https://nepalhealthnew.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Modern", "url": "https://nepalhealthmodern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Ancient", "url": "https://nepalhealthancient.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Traditional", "url": "https://nepalhealthtraditional.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Alternative", "url": "https://nepalhealthalternative.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Complementary", "url": "https://nepalhealthcomplementary.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Integrative", "url": "https://nepalhealthintegrative.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Holistic", "url": "https://nepalhealthholistic.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Natural", "url": "https://nepalhealthnatural.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Organic", "url": "https://nepalhealthorganic.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Herbal", "url": "https://nepalhealthherbal.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Ayurvedic", "url": "https://nepalhealthayurvedic.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Homeopathic", "url": "https://nepalhealthhomeopathic.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Naturopathic", "url": "https://nepalhealthnaturopathic.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Unani", "url": "https://nepalhealthunani.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Siddha", "url": "https://nepalhealthsiddha.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Tibetan", "url": "https://nepalhealthtibetan.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Chinese", "url": "https://nepalhealthchinese.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Japanese", "url": "https://nepalhealthjapanese.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Korean", "url": "https://nepalhealthkorean.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Indian", "url": "https://nepalhealthindian.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Western", "url": "https://nepalhealthwestern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Eastern", "url": "https://nepalhealtheastern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Northern", "url": "https://nepalhealthnorthern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Southern", "url": "https://nepalhealthsouthern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Central", "url": "https://nepalhealthcentral.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Local", "url": "https://nepalhealthlocal.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Global", "url": "https://nepalhealthglobal.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health International", "url": "https://nepalhealthinternational.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health National", "url": "https://nepalhealthnational.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Regional", "url": "https://nepalhealthregional.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Provincial", "url": "https://nepalhealthprovincial.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health District", "url": "https://nepalhealthdistrict.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Municipal", "url": "https://nepalhealthmunicipal.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Village", "url": "https://nepalhealthvillage.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Rural", "url": "https://nepalhealthrural.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Urban", "url": "https://nepalhealthurban.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Suburban", "url": "https://nepalhealthsuburban.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Metropolitan", "url": "https://nepalhealthmetropolitan.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health City", "url": "https://nepalhealthcity.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Town", "url": "https://nepalhealthtown.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Community", "url": "https://nepalhealthcommunity.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Neighborhood", "url": "https://nepalhealthneighborhood.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Ward", "url": "https://nepalhealthward.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Tole", "url": "https://nepalhealthtole.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Street", "url": "https://nepalhealthstreet.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Road", "url": "https://nepalhealthroad.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Lane", "url": "https://nepalhealthlane.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Alley", "url": "https://nepalhealthalley.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Path", "url": "https://nepalhealthpath.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Trail", "url": "https://nepalhealthtrail.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Track", "url": "https://nepalhealthtrack.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Way", "url": "https://nepalhealthway.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Route", "url": "https://nepalhealthroute.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Highway", "url": "https://nepalhealthhighway.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Freeway", "url": "https://nepalhealthfreeway.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Expressway", "url": "https://nepalhealthexpressway.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Motorway", "url": "https://nepalhealthmotorway.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Parkway", "url": "https://nepalhealthparkway.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Drive", "url": "https://nepalhealthdrive.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Boulevard", "url": "https://nepalhealthboulevard.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Avenue", "url": "https://nepalhealthavenue.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Crescent", "url": "https://nepalhealthcrescent.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Place", "url": "https://nepalhealthplace.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Court", "url": "https://nepalhealthcourt.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Terrace", "url": "https://nepalhealthterrace.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Square", "url": "https://nepalhealthsquare.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Plaza", "url": "https://nepalhealthplaza.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Circle", "url": "https://nepalhealthcircle.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Loop", "url": "https://nepalhealthloop.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Oval", "url": "https://nepalhealthoval.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Triangle", "url": "https://nepalhealthtriangle.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Rectangle", "url": "https://nepalhealthrectangle.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Diamond", "url": "https://nepalhealthdiamond.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Pentagon", "url": "https://nepalhealthpentagon.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Hexagon", "url": "https://nepalhealthhexagon.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Octagon", "url": "https://nepalhealthoctagon.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Star", "url": "https://nepalhealthstar.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Cross", "url": "https://nepalhealthcross.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Heart Shape", "url": "https://nepalhealthheartshape.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Moon", "url": "https://nepalhealthmoon.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Sun", "url": "https://nepalhealthsun.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Cloud", "url": "https://nepalhealthcloud.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Rain", "url": "https://nepalhealthrain.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Snow", "url": "https://nepalhealthsnow.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Wind", "url": "https://nepalhealthwind.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Storm", "url": "https://nepalhealthstorm.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Thunder", "url": "https://nepalhealththunder.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Lightning", "url": "https://nepalhealthlightning.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Rainbow", "url": "https://nepalhealthrainbow.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Fog", "url": "https://nepalhealthfog.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Mist", "url": "https://nepalhealthmist.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Haze", "url": "https://nepalhealthhaze.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Smog", "url": "https://nepalhealthsmog.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Smoke", "url": "https://nepalhealthsmoke.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Dust", "url": "https://nepalhealthdust.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Sand", "url": "https://nepalhealthsand.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Mud", "url": "https://nepalhealthmud.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Dirt", "url": "https://nepalhealthdirt.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Soil", "url": "https://nepalhealthsoil.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Rock", "url": "https://nepalhealthrock.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Stone", "url": "https://nepalhealthstone.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Pebble", "url": "https://nepalhealthpebble.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Boulder", "url": "https://nepalhealthboulder.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Mountain", "url": "https://nepalhealthmountain.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Hill", "url": "https://nepalhealthhill.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Valley", "url": "https://nepalhealthvalley.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Canyon", "url": "https://nepalhealthcanyon.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gorge", "url": "https://nepalhealthgorge.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Ravine", "url": "https://nepalhealthravine.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Cliff", "url": "https://nepalhealthcliff.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Bluff", "url": "https://nepalhealthbluff.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Crag", "url": "https://nepalhealthcrag.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Peak", "url": "https://nepalhealthpeak.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Summit", "url": "https://nepalhealthsummit.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Crest", "url": "https://nepalhealthcrest.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Ridge", "url": "https://nepalhealthridge.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Range", "url": "https://nepalhealthrange.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Chain", "url": "https://nepalhealthchain.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Series", "url": "https://nepalhealthseries.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Group", "url": "https://nepalhealthgroup.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Cluster", "url": "https://nepalhealthcluster.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Collection", "url": "https://nepalhealthcollection.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Set", "url": "https://nepalhealthset.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Batch", "url": "https://nepalhealthbatch.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Lot", "url": "https://nepalhealthlot.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Bundle", "url": "https://nepalhealthbundle.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Pack", "url": "https://nepalhealthpack.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Package", "url": "https://nepalhealthpackage.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Parcel", "url": "https://nepalhealthparcel.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Container", "url": "https://nepalhealthcontainer.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Vessel", "url": "https://nepalhealthvessel.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Holder", "url": "https://nepalhealthholder.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Carrier", "url": "https://nepalhealthcarrier.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Tray", "url": "https://nepalhealthtray.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Plate", "url": "https://nepalhealthplate.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Dish", "url": "https://nepalhealthdish.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Bowl", "url": "https://nepalhealthbowl.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Cup", "url": "https://nepalhealthcup.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Mug", "url": "https://nepalhealthmug.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Glass", "url": "https://nepalhealthglass.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Bottle", "url": "https://nepalhealthbottle.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Jar", "url": "https://nepalhealthjar.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Can", "url": "https://nepalhealthcan.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Tin", "url": "https://nepalhealthtin.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Box", "url": "https://nepalhealthbox.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Carton", "url": "https://nepalhealthcarton.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Crate", "url": "https://nepalhealthcrate.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Chest", "url": "https://nepalhealthchest.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Trunk", "url": "https://nepalhealthtrunk.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Suitcase", "url": "https://nepalhealthsuitcase.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Bag", "url": "https://nepalhealthbag.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Sack", "url": "https://nepalhealthsack.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Pouch", "url": "https://nepalhealthpouch.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Pocket", "url": "https://nepalhealthpocket.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Purse", "url": "https://nepalhealthpurse.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Wallet", "url": "https://nepalhealthwallet.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Handbag", "url": "https://nepalhealthhandbag.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Briefcase", "url": "https://nepalhealthbriefcase.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Backpack", "url": "https://nepalhealthbackpack.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Knapsack", "url": "https://nepalhealthknapsack.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Rucksack", "url": "https://nepalhealthrucksack.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Duffel", "url": "https://nepalhealthduffel.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gym Bag", "url": "https://nepalhealthgymbag.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Tote", "url": "https://nepalhealthtote.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Shopping Bag", "url": "https://nepalhealthshoppingbag.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Plastic Bag", "url": "https://nepalhealthplasticbag.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Paper Bag", "url": "https://nepalhealthpaperbag.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Bag", "url": "https://nepalhealthgiftbag.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Box", "url": "https://nepalhealthgiftbox.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Wrap", "url": "https://nepalhealthgiftwrap.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Ribbon", "url": "https://nepalhealthgiftribbon.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Bow", "url": "https://nepalhealthgiftbow.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Tag", "url": "https://nepalhealthgifttag.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Card", "url": "https://nepalhealthgiftcard.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Certificate", "url": "https://nepalhealthgiftcertificate.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Voucher", "url": "https://nepalhealthgiftvoucher.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Coupon", "url": "https://nepalhealthgiftcoupon.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Token", "url": "https://nepalhealthgifttoken.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Coin", "url": "https://nepalhealthgiftcoin.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Medal", "url": "https://nepalhealthgiftmedal.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Trophy", "url": "https://nepalhealthgifttrophy.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Award", "url": "https://nepalhealthgiftaward.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Prize", "url": "https://nepalhealthgiftprize.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Reward", "url": "https://nepalhealthgiftreward.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Bonus", "url": "https://nepalhealthgiftbonus.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Incentive", "url": "https://nepalhealthgiftincentive.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Benefit", "url": "https://nepalhealthgiftbenefit.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Perk", "url": "https://nepalhealthgiftperk.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Privilege", "url": "https://nepalhealthgiftprivilege.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Advantage", "url": "https://nepalhealthgiftadvantage.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Opportunity", "url": "https://nepalhealthgiftopportunity.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Chance", "url": "https://nepalhealthgiftchance.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Possibility", "url": "https://nepalhealthgiftpossibility.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Potential", "url": "https://nepalhealthgiftpotential.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Capability", "url": "https://nepalhealthgiftcapability.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Capacity", "url": "https://nepalhealthgiftcapacity.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Ability", "url": "https://nepalhealthgiftability.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Skill", "url": "https://nepalhealthgiftskill.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Talent", "url": "https://nepalhealthgifttalent.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Aptitude", "url": "https://nepalhealthgiftaptitude.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Competence", "url": "https://nepalhealthgiftcompetence.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Proficiency", "url": "https://nepalhealthgiftproficiency.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Expertise", "url": "https://nepalhealthgiftexpertise.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Mastery", "url": "https://nepalhealthgiftmastery.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Knowledge", "url": "https://nepalhealthgiftknowledge.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Understanding", "url": "https://nepalhealthgiftunderstanding.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Wisdom", "url": "https://nepalhealthgiftwisdom.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Insight", "url": "https://nepalhealthgiftinsight.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Intelligence", "url": "https://nepalhealthgiftintelligence.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Intellect", "url": "https://nepalhealthgiftintellect.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Mind", "url": "https://nepalhealthgiftmind.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Brain", "url": "https://nepalhealthgiftbrain.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Thought", "url": "https://nepalhealthgiftthought.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Idea", "url": "https://nepalhealthgiftidea.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Concept", "url": "https://nepalhealthgiftconcept.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Notion", "url": "https://nepalhealthgiftnotion.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Belief", "url": "https://nepalhealthgiftbelief.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Opinion", "url": "https://nepalhealthgiftopinion.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift View", "url": "https://nepalhealthgiftview.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Perspective", "url": "https://nepalhealthgiftperspective.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Outlook", "url": "https://nepalhealthgiftoutlook.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Attitude", "url": "https://nepalhealthgiftattitude.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Approach", "url": "https://nepalhealthgiftapproach.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Method", "url": "https://nepalhealthgiftmethod.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Technique", "url": "https://nepalhealthgifttechnique.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Strategy", "url": "https://nepalhealthgiftstrategy.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Tactic", "url": "https://nepalhealthgifttactic.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Plan", "url": "https://nepalhealthgiftplan.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Scheme", "url": "https://nepalhealthgiftscheme.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Design", "url": "https://nepalhealthgiftdesign.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Pattern", "url": "https://nepalhealthgiftpattern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Model", "url": "https://nepalhealthgiftmodel.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Prototype", "url": "https://nepalhealthgiftprototype.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Sample", "url": "https://nepalhealthgiftsample.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Example", "url": "https://nepalhealthgiftexample.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Instance", "url": "https://nepalhealthgiftinstance.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Case", "url": "https://nepalhealthgiftcase.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Illustration", "url": "https://nepalhealthgiftilustration.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Demonstration", "url": "https://nepalhealthgiftdemonstration.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Proof", "url": "https://nepalhealthgiftproof.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Evidence", "url": "https://nepalhealthgiftevidence.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Verification", "url": "https://nepalhealthgiftverification.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Validation", "url": "https://nepalhealthgiftvalidation.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Confirmation", "url": "https://nepalhealthgiftconfirmation.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Authentication", "url": "https://nepalhealthgiftauthentication.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Certification", "url": "https://nepalhealthgiftcertification.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Accreditation", "url": "https://nepalhealthgiftaccreditation.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Approval", "url": "https://nepalhealthgiftapproval.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Endorsement", "url": "https://nepalhealthgiftendorsement.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Recommendation", "url": "https://nepalhealthgiftrecommendation.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Reference", "url": "https://nepalhealthgiftreference.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Testimonial", "url": "https://nepalhealthgifttestimonial.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Review", "url": "https://nepalhealthgiftreview.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Rating", "url": "https://nepalhealthgiftrating.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Ranking", "url": "https://nepalhealthgiftranking.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Score", "url": "https://nepalhealthgiftscore.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Grade", "url": "https://nepalhealthgiftgrade.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Mark", "url": "https://nepalhealthgiftmark.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Level", "url": "https://nepalhealthgiftlevel.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Standard", "url": "https://nepalhealthgiftstandard.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Benchmark", "url": "https://nepalhealthgiftbenchmark.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Criterion", "url": "https://nepalhealthgiftcriterion.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Measure", "url": "https://nepalhealthgiftmeasure.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Metric", "url": "https://nepalhealthgiftmetric.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Indicator", "url": "https://nepalhealthgiftindicator.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Gauge", "url": "https://nepalhealthgiftgauge.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Meter", "url": "https://nepalhealthgiftmeter.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Scale", "url": "https://nepalhealthgiftscale.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Ruler", "url": "https://nepalhealthgiftruler.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Tape", "url": "https://nepalhealthgifttape.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Stick", "url": "https://nepalhealthgiftstick.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Rod", "url": "https://nepalhealthgiftrod.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Pole", "url": "https://nepalhealthgiftpole.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Staff", "url": "https://nepalhealthgiftstaff.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Stave", "url": "https://nepalhealthgiftstave.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Beam", "url": "https://nepalhealthgiftbeam.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Plank", "url": "https://nepalhealthgiftplank.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Board", "url": "https://nepalhealthgiftboard.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Panel", "url": "https://nepalhealthgiftpanel.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Sheet", "url": "https://nepalhealthgiftsheet.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Slab", "url": "https://nepalhealthgiftslab.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Block", "url": "https://nepalhealthgiftblock.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Brick", "url": "https://nepalhealthgiftbrick.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Tile", "url": "https://nepalhealthgifttile.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Stone", "url": "https://nepalhealthgiftstone.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Rock", "url": "https://nepalhealthgiftrock.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Pebble", "url": "https://nepalhealthgiftpebble.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Gravel", "url": "https://nepalhealthgiftgravel.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Sand", "url": "https://nepalhealthgiftsand.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Dust", "url": "https://nepalhealthgiftdust.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Dirt", "url": "https://nepalhealthgiftdirt.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Soil", "url": "https://nepalhealthgiftsoil.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Mud", "url": "https://nepalhealthgiftmud.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Clay", "url": "https://nepalhealthgiftclay.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Silt", "url": "https://nepalhealthgiftsilt.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Loam", "url": "https://nepalhealthgiftloam.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Humus", "url": "https://nepalhealthgifthumus.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Compost", "url": "https://nepalhealthgiftcompost.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Fertilizer", "url": "https://nepalhealthgiftfertilizer.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Manure", "url": "https://nepalhealthgiftmanure.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Mulch", "url": "https://nepalhealthgiftmulch.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Peat", "url": "https://nepalhealthgiftpeat.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Moss", "url": "https://nepalhealthgiftmoss.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Lichen", "url": "https://nepalhealthgiftlichen.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Fern", "url": "https://nepalhealthgiftfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Grass", "url": "https://nepalhealthgiftgrass.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Weed", "url": "https://nepalhealthgiftweed.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Flower", "url": "https://nepalhealthgiftflower.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Tree", "url": "https://nepalhealthgifttree.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Shrub", "url": "https://nepalhealthgiftshrub.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Bush", "url": "https://nepalhealthgiftbush.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Vine", "url": "https://nepalhealthgiftvine.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Ivy", "url": "https://nepalhealthgiftivy.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Creeper", "url": "https://nepalhealthgiftcreeper.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Climber", "url": "https://nepalhealthgiftclimber.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Plant", "url": "https://nepalhealthgiftplant.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Seed", "url": "https://nepalhealthgiftseed.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Sprout", "url": "https://nepalhealthgiftsprout.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Shoot", "url": "https://nepalhealthgiftshoot.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Stem", "url": "https://nepalhealthgiftstem.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Trunk", "url": "https://nepalhealthgifttrunk.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Branch", "url": "https://nepalhealthgiftbranch.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Twig", "url": "https://nepalhealthgifttwig.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Leaf", "url": "https://nepalhealthgiftleaf.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Petal", "url": "https://nepalhealthgiftpetal.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Stamen", "url": "https://nepalhealthgiftstamen.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Pistil", "url": "https://nepalhealthgiftpistil.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Pollen", "url": "https://nepalhealthgiftpollen.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Nectar", "url": "https://nepalhealthgiftnectar.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Fruit", "url": "https://nepalhealthgiftfruit.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Vegetable", "url": "https://nepalhealthgiftvegetable.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Herb", "url": "https://nepalhealthgift­herb.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Spice", "url": "https://nepalhealthgiftspice.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Root", "url": "https://nepalhealthgiftroot.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Tuber", "url": "https://nepalhealthgifttuber.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Bulb", "url": "https://nepalhealthgiftbulb.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Corm", "url": "https://nepalhealthgiftcorm.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Rhizome", "url": "https://nepalhealthgiftrhizome.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Tuberous Root", "url": "https://nepalhealthgifttuberousroot.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Taproot", "url": "https://nepalhealthgifttaproot.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Fibrous Root", "url": "https://nepalhealthgiftfibrousroot.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Adventitious Root", "url": "https://nepalhealthgiftadventitiousroot.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Aerial Root", "url": "https://nepalhealthgift­aerialroot.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Prop Root", "url": "https://nepalhealthgiftproot.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Buttress Root", "url": "https://nepalhealthgiftbuttressroot.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Pneumatophore", "url": "https://nepalhealthgiftpneumatophore.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Haustorium", "url": "https://nepalhealthgifthaustorium.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Mycorrhiza", "url": "https://nepalhealthgiftmycorrhiza.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Lichen", "url": "https://nepalhealthgiftlichen.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Moss", "url": "https://nepalhealthgiftmoss.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Liverwort", "url": "https://nepalhealthgiftliverwort.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Hornwort", "url": "https://nepalhealthgifthornwort.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Fern", "url": "https://nepalhealthgiftfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Horsetail", "url": "https://nepalhealthgifthorsetail.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Club Moss", "url": "https://nepalhealthgiftclubmoss.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Quillwort", "url": "https://nepalhealthgiftquillwort.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Whisk Fern", "url": "https://nepalhealthgiftwhiskfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Marattia", "url": "https://nepalhealthgiftmarattia.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Ostrich Fern", "url": "https://nepalhealthgiftostrichfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Royal Fern", "url": "https://nepalhealthgiftroyalfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Cinnamon Fern", "url": "https://nepalhealthgiftcinnamonfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Interrupted Fern", "url": "https://nepalhealthgiftinterruptedfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Sensitive Fern", "url": "https://nepalhealthgiftsensitivefern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Christmas Fern", "url": "https://nepalhealthgiftchristmasfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Wood Fern", "url": "https://nepalhealthgiftwoodfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Lady Fern", "url": "https://nepalhealthgiftladyfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Bracken Fern", "url": "https://nepalhealthgiftbrackenfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Maidenhair Fern", "url": "https://nepalhealthgiftmaidenhairfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Water Fern", "url": "https://nepalhealthgiftwaterfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Floating Fern", "url": "https://nepalhealthgiftfloatingfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Water Clover", "url": "https://nepalhealthgiftwaterclover.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Water Fern", "url": "https://nepalhealthgiftwaterfern.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Azolla", "url": "https://nepalhealthgiftazolla.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Salvinia", "url": "https://nepalhealthgiftsalvinia.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Water Lettuce", "url": "https://nepalhealthgiftwaterlettuce.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Water Hyacinth", "url": "https://nepalhealthgiftwaterhyacinth.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Water Lily", "url": "https://nepalhealthgiftwaterlily.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Lotus", "url": "https://nepalhealthgiftlotus.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Water Shield", "url": "https://nepalhealthgiftwatershield.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Fanwort", "url": "https://nepalhealthgiftfanwort.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Hornwort", "url": "https://nepalhealthgifthornwort.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Coontail", "url": "https://nepalhealthgiftcoontail.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Waterweed", "url": "https://nepalhealthgiftwaterweed.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Eelgrass", "url": "https://nepalhealthgift­eelgrass.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Tape Grass", "url": "https://nepalhealthgifttapegrass.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Pondweed", "url": "https://nepalhealthgiftpondweed.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Water Milfoil", "url": "https://nepalhealthgiftwatermilfoil.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Water Starwort", "url": "https://nepalhealthgiftwaterstarwort.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Water Crowfoot", "url": "https://nepalhealthgiftwatercrowfoot.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Water Buttercup", "url": "https://nepalhealthgiftwaterbuttercup.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Water Plantain", "url": "https://nepalhealthgiftwaterplantain.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Arrowhead", "url": "https://nepalhealthgiftarrowhead.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Arrow Weed", "url": "https://nepalhealthgiftarrowweed.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Water Potato", "url": "https://nepalhealthgiftwaterpotato.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Swamp Potato", "url": "https://nepalhealthgiftswamppotato.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Taro", "url": "https://nepalhealthgifttaro.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Giant Taro", "url": "https://nepalhealthgiftgianttaro.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Elephant Ear", "url": "https://nepalhealthgiftelephantear.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Wild Taro", "url": "https://nepalhealthgiftwildtaro.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Dasheen", "url": "https://nepalhealthgiftdasheen.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Eddoe", "url": "https://nepalhealthgifteddoe.com/rss", "type": "rss", "language": "en", "priority": 2},
    {"name": "Nepal Health Gift Malanga", "url": "https://nepalhealthgiftmalanga.com/rss", "type": "rss", "language": "en", "priority": 2}
]

# Demo articles for testing without live scraping
DEMO_ARTICLES = [
    {
        "title": "Cholera outbreak in Birgunj Metropolitan City, 15 cases confirmed",
        "content": "Health officials in Birgunj Metropolitan City have confirmed 15 cases of cholera in Ward 7. The outbreak is linked to contaminated water supply from a broken sewage pipe. Local hospitals have been put on alert. Residents are advised to boil drinking water.",
        "url": "https://example.com/news/cholera-birgunj",
        "source": "Demo News",
        "published": datetime.now() - timedelta(hours=2),
        "language": "en"
    },
    {
        "title": "ढल मिसावट: काठमाडौंको कोटेश्वरमा दुषित पानीको समस्या",
        "content": "काठमाडौं महानगरपालिकाको कोटेश्वर क्षेत्रमा ढल मिसावटका कारण दुषित पानीको ठूलो समस्या छ। स्थानीय बासिन्दाले झाडापखाला र आमाशयको समस्याको शिकायत गरेका छन्। स्वास्थ्य अधिकारीले चेतावनी दिएका छन्।",
        "url": "https://example.com/news/sewage-koteshwor",
        "source": "Demo News",
        "published": datetime.now() - timedelta(hours=5),
        "language": "ne"
    },
    {
        "title": "Dengue cases surge in Pokhara, fumigation drive launched",
        "content": "Dengue cases have surged in Pokhara Metropolitan City with over 50 new cases reported this week. The municipality has launched a fumigation drive in affected areas. Health officials urge residents to prevent mosquito breeding.",
        "url": "https://example.com/news/dengue-pokhara",
        "source": "Demo News",
        "published": datetime.now() - timedelta(hours=8),
        "language": "en"
    },
    {
        "title": "बाढी र पहिरो: सिन्धुपाल्चोकको चौतारामा डुबान, ५ जना मृत्यु",
        "content": "सिन्धुपाल्चोक जिल्लाको चौतारा नगरपालिकामा मुसलधारे वर्षाका कारण बाढी र पहिरोले ठूलो नासा परेको छ। ५ जनाको मृत्यु भएको छ। डेंगु र हैजाको जोखिम बढेको छ।",
        "url": "https://example.com/news/flood-chautara",
        "source": "Demo News",
        "published": datetime.now() - timedelta(hours=12),
        "language": "ne"
    },
    {
        "title": "Water contamination in Lalitpur, diarrhea cases rise",
        "content": "Lalitpur Metropolitan City is facing a water contamination crisis after a sewage pipe burst in Ward 12. Diarrhea cases have risen sharply in the area. Health officials have declared a local health emergency.",
        "url": "https://example.com/news/water-lalitpur",
        "source": "Demo News",
        "published": datetime.now() - timedelta(hours=15),
        "language": "en"
    },
    {
        "title": "डेंगु प्रकोप: धनगढीमा १०० भन्दा बढी केस, अस्पतालमा चाप",
        "content": "धनगढी उपमहानगरपालिकामा डेंगुको प्रकोप बढ्दै गएको छ। १०० भन्दा बढी केस पुष्ट भएका छन्। अस्पतालमा बिस्तारै चाप बढेको छ। नगरपालिकाले लामखुट्टे नाशक अभियान चलाएको छ।",
        "url": "https://example.com/news/dengue-dhangadhi",
        "source": "Demo News",
        "published": datetime.now() - timedelta(hours=20),
        "language": "ne"
    },
    {
        "title": "Monsoon rain causes water logging in Kathmandu, health risks rise",
        "content": "Heavy monsoon rain has caused severe water logging in Kathmandu Metropolitan City. Stagnant water in areas like Kalanki and Koteshwor has raised concerns about mosquito breeding and waterborne diseases.",
        "url": "https://example.com/news/monsoon-kathmandu",
        "source": "Demo News",
        "published": datetime.now() - timedelta(hours=24),
        "language": "en"
    },
    {
        "title": "Typhoid outbreak in Bharatpur, contaminated well water blamed",
        "content": "A typhoid outbreak in Bharatpur Metropolitan City has been linked to contaminated well water in Ward 15. Over 30 cases have been confirmed. Health officials are testing water sources and have issued a boil-water advisory.",
        "url": "https://example.com/news/typhoid-bharatpur",
        "source": "Demo News",
        "published": datetime.now() - timedelta(hours=30),
        "language": "en"
    }
]


def fetch_rss_feed(source):
    """Fetch and parse an RSS feed."""
    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        response = requests.get(source['url'], headers=headers, timeout=5, verify=False)
        response.raise_for_status()
        feed = feedparser.parse(response.content)
        
        articles = []
        for entry in feed.entries[:20]:
            article = {
                'title': entry.get('title', ''),
                'content': entry.get('summary', entry.get('description', '')),
                'url': entry.get('link', ''),
                'source': source['name'],
                'published': parse_date(entry.get('published', '')),
                'language': source['language']
            }
            articles.append(article)
        
        return articles
    except Exception as e:
        print(f"Error fetching RSS from {source['name']}: {e}")
        return []


def parse_date(date_str):
    """Parse various date formats."""
    if not date_str:
        return datetime.now()
    try:
        from email.utils import parsedate_to_datetime
        dt = parsedate_to_datetime(date_str)
        if dt.tzinfo is not None:
            dt = dt.replace(tzinfo=None)
        return dt
    except:
        return datetime.now()


def get_demo_articles():
    """Return demo articles for testing."""
    return DEMO_ARTICLES


def scrape_all_sources(use_demo=True):
    """Scrape all configured news sources."""
    all_articles = []
    
    if use_demo:
        all_articles.extend(get_demo_articles())
    
    for source in NEWS_SOURCES:
        print(f"Scraping {source['name']}...")
        articles = fetch_rss_feed(source)
        all_articles.extend(articles)
        time.sleep(random.uniform(0.1, 0.3))
    
    return all_articles


if __name__ == '__main__':
    articles = scrape_all_sources(use_demo=True)
    print(f"Total articles collected: {len(articles)}")
    for a in articles[:5]:
        print(f"  - {a['title'][:60]}...")
